# Development Docker Compose (Database only - app runs locally)
version: "3.9"

services:
  MRMPG-postgres-dev:
    image: postgres:alpine
    container_name: mrmpg_dev
    restart: always
    environment:
      POSTGRES_USER: mrmpg_dev
      POSTGRES_PASSWORD: mrmpg
      POSTGRES_DB: mrmpg_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mrmpg_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mrmpg-dev

networks:
  mrmpg-dev:
    driver: bridge

volumes:
  pg_data:
